import Head from 'next/head';
import Image from 'next/image';
// @ts-ignore
import {ICONS, IMAGES} from "public/images";
import Layout from "../../components/layouts/profile-layout";
// @ts-ignore
import {userBgIcon} from "/public/images/icons";
// @ts-ignore
import Cards from "/public/images/icons/nav/navCards";
// @ts-ignore
import Points from "/public/images/icons/nav/navPoints";
// @ts-ignore// @ts-ignore
import React, {useEffect, useState} from "react";
import TicketItem from "../../components/blocks/ticket-item";
import {DatePicker, Form, Input, Modal, Rate, Select} from "antd";
import Button from "../../components/UI/button";
import dayjs from 'dayjs';

import weekday from "dayjs/plugin/weekday"
import localeData from "dayjs/plugin/localeData"
import ChangeAvatar from "../../components/UI/modal/ChangeAvatar";
import {useSelector} from "react-redux";
import axios from "axios";
import {getUserInfo} from "../../components/slices/userSlice";

dayjs.extend(weekday)
dayjs.extend(localeData)
const dateFormat = 'YYYY-MM-DD';

export default function Profile() {
  const baseApi = process.env.baseApi;


  const [isDisabledEmail, setIsDisabledEmail] = useState<boolean>(true);
  const [cities, setCities] = useState<any>([
    {
      "id": 1,
      "title": "Abasha"
    },
    {
      "id": 2,
      "title": "Adigeni"
    }

  ]);
  const [isModalOpen, setIsModalOpen] = useState<boolean>(false);
  const [isOpenChooseModal, setIsOpenChooseModal] = useState<boolean>(false);
  const [error, setError] = useState<boolean>(false);
  const userInfo = useSelector((state: any) => state.user.userInfo);
  const [profileForm] = Form.useForm();
  const [codeForm] = Form.useForm();
  const {Option} = Select;

  useEffect(() => {
    axios.get(`${baseApi}/user/municipalities`).then((res) => {
      setCities(res.data)
    })

  }, [userInfo])

  const onFinish = (fieldsValue: any) => {
    const values = {
      ...fieldsValue,
      'personDbo': fieldsValue['personDbo']?.format('YYYY-MM-DD'),
      uuid: fieldsValue['personalId'],
      contactInfo: [
        {
          "regId": 2000248,
          "prefix": "995",
          "value": fieldsValue['phone']?.toString(),
          "info": "my phone number",
          "contactInfoType": "phone",
          "contactInfoTag": "main",
          "serviceType": "personal"
        },
        {
          "regId": 2000248,
          "prefix": "mail",
          "value": fieldsValue['email']?.toString(),
          "info": "my mail ",
          "contactInfoType": "mail",
          "contactInfoTag": "work",
          "serviceType": "personal"
        }
      ]
    };

    delete values.email;
    delete values.phone;


    axios.post(`${baseApi}/user/user/uuuu`, values)
        .then((res) => {
          console.log("resss", res)
          // @ts-ignore
          dispatch(getUserInfo())
          setIsOpenChooseModal(false)

        })

    console.log("values", values)

  };

  const onFinishCode = (values) => {
    console.log("codeval", values)
  }

  const openCodeModal = () => {
    setIsModalOpen(true)
  }
  const handleCancel = () => {
    setIsModalOpen(false)
  }

  return (
      <>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app"/>
          <link rel="icon" href="/public/favicon.ico"/>
        </Head>
        <Modal
            className={"codeModel"}
            open={isModalOpen}
            onCancel={handleCancel}
            footer={""}
            title={""}
            width={487}>
          <p className={"text-[24px] text-dark font-bold"}>ელ-ფოსტის შეცვლა</p>
          <div className={"p-[25px] mt-[42px] pt-0 pb-0"}>
            <p className={"text-dark6 text-[14px]"}>
              ერთჯერადი კოდი გამოგზავნილია
              მითითებულ მეილზე , გთხოვთ გადაამოწმოთ.</p>
            <Form
                className={"w-full col-span-2 point-filter"}
                form={codeForm}
                layout="vertical"
                onFinish={onFinishCode}
            >
              <div className={"flex flex-col w-full point-filter mt-[21px]"}>
                <Form.Item label="ერთჯერადი კოდი" name={"code"}
                           rules={[
                             {
                               required: true,
                               message: "ველი სავალდებულოა"
                             }
                           ]}
                >
                  <Input
                      type={"number"}
                      placeholder="შეიყვანე ერთჯერადი კოდი"/>
                </Form.Item>
                {error && <p className={"text-red"}>კოდი არასწორია,სცადეთ თავიდან</p>}

                <button type={"submit"}
                        className={"bg-red px-[32px] h-[48px] w-min self-end mt-[6px] rounded-xl cursor-pointer"}>
                  <p className={"text-[white]"}>შეინახე</p>
                </button>

              </div>
            </Form>

          </div>

        </Modal>

        <ChangeAvatar setIsOpenChooseModal={setIsOpenChooseModal} isOpenChooseModal={isOpenChooseModal}/>

        <div className={"w-full"}>

          <h2 className={"text-[32px] text-[#383838] font-bold"}>
            პერსონალური ინფორმაცია
          </h2>

          <div className={"gap-x-[30px] grid grid-cols-3 h-[2000px] mt-[40px]"}>
            <div className={""}>
              <div className={"bg-red rounded-xl cursor-pointer"} onClick={() => setIsOpenChooseModal(true)}>
                <img src={IMAGES.bigAvatar.src} alt={""}/>
              </div>
              <p className={"text-dark6 mt-[14px] text-[14px]"}>ავატარის შესაცვლელად დააკლიკე ფოტოს</p>
            </div>

            <Form
                className={"w-full col-span-2 point-filter profileInputs"}
                form={profileForm}
                layout="vertical"
                // onChange={onFinish}
                initialValues={{
                  firstName: userInfo?.details?.firstName,
                  email: "b_kokhodze2@cu.edu.ge",
                  personDbo: dayjs('2015-01-01', dateFormat),
                  city: 4,
                  personalId: "543",
                  lastName: userInfo?.details?.lastName,
                  phone: "სახელი",
                  gender: userInfo?.details?.gender,
                  address: "address",
                }}
                onFinish={onFinish}
            >
              <div className={"grid grid-cols-2 gap-x-[30px] "}>
                <div className={"space-y-[30px]"}>
                  <Form.Item label="სახელი" name={"firstName"}
                             rules={[
                               {
                                 required: true,
                                 message: "ველი სავალდებულოა"
                               }
                             ]}
                  >
                    <Input
                        placeholder="სახელი"/>
                  </Form.Item>

                  {/*{*/}
                  {/*  isDisabledEmail ? <div className={"w-full"} onClick={() => openCodeModal()}>*/}
                  {/*    <p className={"text-[#38383899] text-[14px] mb-1"}>ელ.ფოსტა</p>*/}
                  {/*    <div*/}
                  {/*        className={"bg-[white] w-full rounded-xl flex items-center pl-6 h-[48px]"}>*/}
                  {/*      d*/}
                  {/*    </div>*/}
                  {/*  </div> : <Form.Item*/}
                  {/*      label="ელ.ფოსტა"*/}
                  {/*      name={"email"}*/}
                  {/*      rules={[*/}
                  {/*        {*/}
                  {/*          type: 'email',*/}
                  {/*          message: 'ემაილი არ არის ვალიდური'*/}
                  {/*        },*/}
                  {/*        {*/}
                  {/*          required: true,*/}
                  {/*          message: "ველი სავალდებულოა"*/}
                  {/*        }*/}
                  {/*      ]}*/}
                  {/*  >*/}
                  {/*    <Input*/}
                  {/*        placeholder="ელ.ფოსტა"/>*/}
                  {/*  </Form.Item>*/}
                  {/*}*/}

                  <Form.Item
                      label="ელ.ფოსტა"
                      name={"email"}
                      rules={[
                        {
                          type: 'email',
                          message: 'ემაილი არ არის ვალიდური'
                        },
                        {
                          required: true,
                          message: "ველი სავალდებულოა"
                        }
                      ]}
                  >
                    <Input
                        placeholder="ელ.ფოსტა"/>
                  </Form.Item>


                  <Form.Item label="დაბადების თარიღი" name={"personDbo"} rules={[
                    {
                      required: true,
                      message: "ველი სავალდებულოა"
                    }
                  ]}>

                    <DatePicker
                        // defaultValue={dayjs('2015-01-01', dateFormat)}
                        format={dateFormat}
                        placeholder={"დაბადების თარიღი"}/>

                  </Form.Item>

                  <Form.Item
                      name="city"
                      label="ქალაქი"
                      rules={[
                        {
                          required: true,
                          message: "ველი სავალდებულოა"
                        }
                      ]}

                  >
                    <Select placeholder="ქალაქი"
                    >
                      {cities?.map((item, index) => {
                        return <Option key={index} value={item?.id}>{item?.title}</Option>
                      })}

                    </Select>
                  </Form.Item>

                  <Form.Item label="პირადი ნომერი" name={"personalId"}
                  >
                    <Input
                        disabled={true}
                        placeholder="პირადი ნომერი"/>
                  </Form.Item>

                </div>
                <div className={"space-y-[30px]"}>
                  <Form.Item label="გვარი" name={"lastName"}
                             rules={[
                               {
                                 required: true,
                                 message: "ველი სავალდებულოა"
                               }
                             ]}>
                    <Input placeholder="გვარი"/>
                  </Form.Item>
                  <Form.Item label="ტელეფონის ნომერი" name={"phone"}
                             rules={[
                               {
                                 required: true,
                                 message: "ველი სავალდებულოა"
                               }
                             ]}>
                    <Input
                        placeholder="ტელეფონის ნომერი"/>
                  </Form.Item>

                  <Form.Item
                      name="gender"
                      label="სქესი"
                      rules={[
                        {
                          required: true,
                          message: "ველი სავალდებულოა"
                        }
                      ]}
                  >
                    <Select placeholder="სქესი">
                      <Option value="m">Male</Option>
                      <Option value="f">Female</Option>
                    </Select>
                  </Form.Item>

                  <Form.Item label="მისამართი" name={"address"}
                             rules={[
                               {
                                 required: true,
                                 message: "ველი სავალდებულოა"
                               }
                             ]}>
                    <Input
                        placeholder="მისამართი"/>
                  </Form.Item>

                </div>
              </div>

              <div className={"flex justify-between items-center mt-[30px]"}>
                <p className={"text-[14px] text-red cursor-pointer"}>პაროლის შეცვლა</p>

                <button type={"submit"} className={"bg-red px-[32px] h-[48px] rounded-xl cursor-pointer"}>
                  <p className={"text-[white]"}>შეინახე</p>
                </button>

                {/*<Button text={"შეინახე"} bgColor={"#DB0060"}/>*/}
              </div>

            </Form>

          </div>

        </div>

      </>
  )
}

Profile.getLayout = function getLayout(page: any) {
  return (
      <Layout>
        {page}
      </Layout>
  )
}