import Head from 'next/head';
import Image from 'next/image';
// @ts-ignore
import {ICONS, IMAGES} from "public/images";
import Layout from "../../components/layouts/profile-layout";
// @ts-ignore
import {userBgIcon} from "/public/images/icons";
// @ts-ignore
import Cards from "/public/images/icons/nav/navCards";
// @ts-ignore
import Points from "/public/images/icons/nav/navPoints";
// @ts-ignore// @ts-ignore
import React, {useEffect} from "react";
import TicketItem from "../../components/blocks/ticket-item";
import axios from "axios";

export default function CardsPage() {

  const addCard = () => {
    axios.post(`https://bog-banking.pirveli.ge/api/bog/saveCard`).then((res) => {
      let link = res?.data?.links[1]?.href;
      typeof window !== 'undefined' && window.open(link, '_self');

    })
  }

  useEffect(() => {
    axios.get(`https://bog-banking.pirveli.ge/api/bog/getSavedCards`).then((res) => {
      console.log("res", res)
    })
  })

  return (
      <div>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app"/>
          <link rel="icon" href="/public/favicon.ico"/>
        </Head>

        <div className={"w-full"}>

          <h2 className={"text-[32px] text-[#383838] font-bold"}>
            გადახდის მეთოდები
          </h2>

          <div className={"gap-x-[30px] grid grid-cols-3 h-[2000px] mt-[40px]"}>
            <div
                className={"w-full bg-[#db006033] rounded-[5px] h-[200px] flex items-center justify-center cursor-pointer"}
                onClick={() => addCard()}>
              <div>
                <p className={"text-red text-center"}>+</p>
                <p className={"text-red text-center"}>დაამატე ბარათი</p>
              </div>
            </div>
            <p>2</p>
            <p>3</p>
          </div>

        </div>

      </div>
  )
}

CardsPage.getLayout = function getLayout(page: any) {
  return (
      <Layout>
        {page}
      </Layout>
  )
}