import Head from 'next/head';
import Image from 'next/image';
// @ts-ignore
import {ICONS, IMAGES} from "public/images";
import Layout from "../../components/layouts/profile-layout";
// @ts-ignore
import {userBgIcon} from "/public/images/icons";
// @ts-ignore
import Cards from "/public/images/icons/nav/navCards";
// @ts-ignore
import Points from "/public/images/icons/nav/navPoints";
// @ts-ignore// @ts-ignore
import React, {useEffect, useState} from "react";
import TicketsItem from "../../components/blocks/ticket-item";
import OrderItem from "../../components/blocks/order-item";
import {Form, Input, Modal, Rate} from "antd";
import axios from "axios";


export default function Profile() {
  const [isModalOpen, setIsModalOpen] = useState<boolean>(false);
  const baseApi = process.env.baseApi;

  const [orders, setOrders] = useState<any>([]);

  const [commentForm] = Form.useForm();
  const {TextArea} = Input;

  const handleCancel = () => {
    commentForm.resetFields();
    setIsModalOpen(false);
  };
  useEffect(() => {
    axios.get(`${baseApi}/user/user/get-user-vouchers`).then((res) => {
      setOrders(res.data)
    }).catch(() => {
      console.log("catch")
    })
  }, [])

  const onFinishComment = (values: object) => {

  }

  return (
      <div>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app"/>
          <link rel="icon" href="/public/favicon.ico"/>
        </Head>
        <Modal
            className={"reviewModal"}
            open={isModalOpen}
            onCancel={handleCancel}
            footer={""}
            title={""}
            width={620}>

          <div className={"flex p-6 bg-[#d9d9d933] rounded-[16px]"}>
            <div className={"w-full max-w-[125px] max-h-[84px] mr-4 relative"}>
              <Image src={IMAGES.offerItem}
                     quality={70}
                     blurDataURL={IMAGES.placeholder.src}
                     placeholder="blur"
                     priority={true}
                     alt={"product image"}
                     className={"rounded-xl"}
                     style={{objectFit: "cover"}}
              />
              {/*<div*/}
              {/*    className={"absolute top-[8px] left-[8px] z-20 flex justify-center items-center bg-[#E35A43] rounded-[100px] h-[25px]"}>*/}
              {/*  <p className={"text-[white] text-[12px] px-[12px]"}>- 50 USD</p>*/}
              {/*</div>*/}
            </div>
            <div>
              <p className={"text-[#383838b3] text-base leading-[16px]"}>#45678</p>
              <h3 className={"text-[#383838] font-bold text-[18px leading-[18px]"}>Campus Alba Castello Mare Hotel &
                Wellness Resort</h3>
              <p className={"text-[#38383899] mt-[8px] text-[14px] leading-[17px]"}>Room for 2 guests from Campus Alba
                Castello Mare Hotel & Wellness Resort!</p>
            </div>

          </div>
          <Form
              form={commentForm}
              onFinish={onFinishComment}
              className={"p-6 pb-[32px] pt-[18px]"}>

            <Form.Item name={"rate"} className={"flex justify-center"}>
              <Rate className={"text-[27px]"}/>
            </Form.Item>

            <Form.Item name={"comment"}>
              <TextArea rows={4}
                        style={{height: 120, resize: 'none'}}
                        placeholder={"კომენტარი"}
                        className={"bg-[#d9d9d91a] rounded-[16px] border-none p-5"}
              />
            </Form.Item>

            <div className={"flex justify-end mt-6 items-center"}>
              <p className={"mr-10 text-[#383838] cursor-pointer"} onClick={handleCancel}>გაუქმება</p>
              <button type={"submit"}
                      className={"flex justify-center items-center rounded-xl bg-red py-4 px-10 cursor-pointer"}>
                <p className={"text-[white]"}>კომენტარის დამატება</p>
              </button>
            </div>

          </Form>

        </Modal>

        <div className={"w-full"}>

          <h2 className={"text-[32px] text-[#383838] font-bold"}>
            ჩემი შეკვეთები
          </h2>

          <div className={"space-y-[30px] h-[2000px] mt-[40px]"}>
            {
              orders.map((e: any, index) => {
                return <OrderItem data={e} setIsModalOpen={setIsModalOpen} key={index} evaluated={index % 2 == 0}/>
              })
            }
          </div>

        </div>

      </div>
  )
}

Profile.getLayout = function getLayout(page: any) {
  return (
      <Layout>
        {page}
      </Layout>
  )
}